### PR TITLE
[#4264] field_name_limit should not expand to 2 columns

### PR DESCRIPTION
**Pull request by hcs0**
Scope
-----

When the field_name takes up more than 14 chars, it expands across two columns instead of staying in the one column.

See ``update_datetime:`` for event id ``20037`` as an example:
https://staging.sftpplus.com/documentation/sftpplus/latest/events/events.html#id35

Detail about the ``field_name_limit`` is at https://github.com/chevah/docutils/blob/763f19d1a33fa750659b1a7f08dc69da9df82c41/docutils/docs/user/config.txt (it states that the default is ``14`` chars)

Changes
-------

The ``field_name`` now stays in 1 column when the text is more than 14 chars.

How to try and test the changes
-------------------------------

reviewers: @adiroiban

### CODE REVIEW

**Comment by hcs0** [comment]
@adiroiban I'm running the same commands to build a new package and testing it in the server repo using https://github.com/chevah/scame/pull/2#issuecomment-299626108 but not seeing results or the new docutils package on the ``server`` repo.  

I was able to successfully build this new package into a tar zip though.

Is there anything else to check this change?

**Comment by hcs0** [comment]
needs-review

**Comment by adiroiban** [comment]
inside the docutils repo you can run

```
python setup.py dist
```

then, go to the repo/project in which you want to use the new docutil package and do

```
./build-*/bin/python -m pip install -U ../path-to/docutils/dist/docutils-VER.tar.gz
```

now you should have the new docutils package installed.
In this way you can test it without having to push a testing package to our public pypi repository

--------

our paver.sh is just create a python virtual-env inside the build-OS-ARCH/ folder

**Comment by hcs0** [comment]
I've read that I need to change ``.docutils.conf``:

```
3. ``~/.docutils``: This is a user-specific configuration file,
   located in the user's home directory.  Settings in this file will
   override corresponding settings in both the system-wide and
   project-specific configuration files.
```

So this change now only changes the two fields since they are 14 as default according to 

https://github.com/chevah/docutils/blob/763f19d1a33fa750659b1a7f08dc69da9df82c41/docutils/docs/user/config.txt

----

Do I need to go through and set up the package again to apply the conf?  Not seeing any changes locally...

The instructions I had to use a custom package is correct (also it should be ``python setup.py sdist``)

**Comment by adiroiban** [comment]
I gave you access to this repo.

Note that this repo is just a sync of the upstream repo 

Our  changes should go in https://github.com/chevah/docutils/tree/docutils-0.12-chevah

-------

We are now using an older docutils version... it might be worth testing the 0.15 version.

For our usage, I don't think that we are using the configuration file. so doing any changes in there will have no effect.

We are not using the docutils directly, but via sphinx. so any configuration changes should go into sphinx

**Comment by hcs0** [comment]
Closing this since changes should go on https://github.com/chevah/docutils/tree/docutils-0.12-chevah

New PR is at https://github.com/hcs0/docutils/pull/1
This PR seeks to merge to the existing branch docutils-0.12-chevah

PR is in work but wanting to check that it's merging to the correct trunk.

-----

> We are now using an older docutils version... it might be worth testing the 0.15 version.

I made a ticket for adding the 0.15 version at https://trac.chevah.com/ticket/4307

**Comment by adiroiban** [comment]
You can change the base of a PR... I just changed it now

**Comment by hcs0** [comment]
Can I reopen this since the base of the PR has changed?

**Pull request closed without merging**
